### ISSUE TITLE
Revisão v3.3.6

### ISSUE THREAD

**Issue by flaviacs** [bootstrapbrasil/bootstrap#2]
**General**
- [ ] Nav main
- [ ] Footer

**Home**
- [ ] Header
- [ ] Features
- [ ] Built with Bootstrap

**Getting started**
- [ ] Header/Sidebar
- [ ] Download
- [ ] What's included
- [ ] Compiling CSS and JavaScript
- [ ] Basic template
- [ ] Examples
- [ ] Tools
- [ ] Community
- [ ] Disabling responsiveness
- [ ] Migrating from 2.x to 3.0
- [ ] Browser and device support
- [ ] Third party support
- [ ] Accessibility
- [ ] License FAQs
- [ ] Translations

**CSS**
- [ ] Header/Sidebar
- [ ] Overview
- [ ] Grid system
- [ ] Typography
- [ ] Code
- [ ] Tables
- [ ] Forms
- [ ] Buttons
- [ ] Images
- [ ] Helper classes
- [ ] Responsive utilities
- [ ] Using Less
- [ ] Using Sass 
  **Components**
- [ ] Header/Sidebar
- [ ] Glyphicons
- [ ] Dropdowns
- [ ] Button groups
- [ ] Button dropdowns
- [ ] Input groups
- [ ] Navs
- [ ] Navbar
- [ ] Breadcrumbs
- [ ] Pagination
- [ ] Labels
- [ ] Badges
- [ ] Jumbotron
- [ ] Page header
- [ ] Thumbnails
- [ ] Alerts
- [ ] Progress bars
- [ ] Media object
- [ ] List group
- [ ] Panels
- [ ] Responsive embed
- [ ] Wells

**JavaScript**
- [ ] Header/Sidebar
- [ ] Overview
- [ ] Transitions
- [ ] Modal
- [ ] Dropdown
- [ ] Scrollspy
- [ ] Tab
- [ ] Tooltip
- [ ] Popover
- [ ] Alert
- [ ] Button
- [ ] Collapse
- [ ] Carousel
- [ ] Affix

**Customize**
- [ ] Header/Sidebar
- [ ] Import
- [ ] Less components
- [ ] jQuery plugins
- [ ] Less variables
- [ ] Download

**Comment by adammacias** [comment]
@bootstrapbrasil/members pessoal, por favor ajudem na revisão no que já foi traduzido #1 :smile:
